replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 150m
    memory: 256Mi

coreServices:
  frontend: true
  frontend-proxy: true
  cart: true
  checkout: true
  payment: true
  product-catalog: true
  shipping: true
  recommendation: true
  accounting: true
  currency: true
  email: true
  flagd: true
  fraud-detection: true
  image-provider: true
  kafka: true
  otel-collector: true

optionalServices:
  grafana: false
  opensearch: false
  jaeger-collector: false
  jaeger-query: false
  load-generator: false
  postgresql: false
  quote: false
  ad: false
  valkey-cart: false
  prometheus: false

frontend:
  service:
    type: LoadBalancer
    port: 8080
